package com.thiernombd.fattelima_class;

import android.util.Log;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Thierno_M_B_DIALLO on 23/11/2017.
 */

public class Alarm {
    public String rtcSecond=null;
    public String libelle=null;
    public String ringFile=null;
    //private enum daysChecked{Lun,Mar,Mer,Jeu,Ven,Sam,Dim};
    //public String repeteDays[]=null;
    public String repeteDays=null;

    public Alarm(String rtcSecond, String libelle, String ringFile, String repeteDays) {
        this.rtcSecond = rtcSecond;
        this.libelle = libelle;
        this.ringFile = ringFile;
        this.repeteDays = repeteDays;
    }

    public static List<Alarm> getAlarmDataList(){
        List<Alarm> data= new ArrayList<Alarm>();
        Alarm[] al = getAlarms();
        Log.i("IIIIIIIIIIIIIIIIIIIII",al[0].libelle);
        Log.i("tTTTTTTTTTTTTTTTTTTTTT",String.valueOf(al.length));
        for (int i=0;i<al.length;i++){
            al[i].libelle = i+" - "+al[i].libelle;
            data.add(al[i]);
        }
        return data;
    }

    private static Alarm[] getAlarms(){
        //String[] repet = new String[]{"Lun. Mar. Mer. Jeu. Ven. Sam. Dim", "erzere"};
        return  new Alarm[]{
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                /*new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("12h:30min","Je dois me reveiller","sdcard/download/myringfile","Lun. Mar. Mer. Jeu. Ven. Sam. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Me reveiller","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Ecouter de la music","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Faire du sport","sdcard/Music/myringfile",""),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Lun. Mar. Ven. Dim"),
                new Alarm("10:00min","Je dois me reveiller tot pout aller blablablabla","myringfile","Lun."),
                new Alarm("10:00min","Aller à l'ecole","sdcard/Music/myringfile","Mar. Ven. Dim"),
                */
        };
    }
}
